name: iKuuu Daily Checkin

on:
  # run automatically every 24 hours
  schedule:
    - cron: '0 */24 * * *'

  push:
    - main

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm i bun -g && bun run start

      - name: Run checkin script
        env:
          IKUUU_API_PATH: ${{ secrets.IKUUU_API_PATH }}
          COOKIE_CLOUD_API_PATH: ${{ secrets.COOKIE_CLOUD_API_PATH }}
          COOKIE_CLOUD_UUID: ${{ secrets.COOKIE_CLOUD_UUID }}
          COOKIE_CLOUD_PASSWORD: ${{ secrets.COOKIE_CLOUD_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: node index.js
